Quiz 3
========================================================

Question 1
----------

```{r}
library(ElemStatLearn)
data(bone)
plot(bone$age,bone$spnbmd,pch=19,col=((bone$gender=="male")+1))
```

This is an exploratory graph because:
* no units on axis labels
* the axis labels are r variables

Question 2
----------

```{r}
library(ElemStatLearn)
data(marketing)
boxplot(marketing$Income ~ marketing$Marital,col="grey",xaxt="n",ylab="Income",xlab="")
axis(side=1,at=1:5,labels=c("Married","Living together/not married","Divorced or separated","Widowed","Nevermarried"),las=2)
```

* 75th income widowded ~= 75th income never married
* median income divorced > median income widowed

Question 3
----------

```{r}
library(datasets)
data(iris)
irisSubset <- iris[,1:4]
hc <- hclust(dist(irisSubset))
table(cutree(hc, h=3))
rect.hclust(hc, h=3)
plot(hc)
```

4 clusters at height 3

Question 4
----------
Help on [k-means clustering](http://tinyurl.com/b32nn94)

```{r}
# read data and subset to x and y columns only
pData <- read.csv("data/quiz3question4.csv")[,2:3] 
plot(pData$x,pData$y,pch=19,col="blue")
# run k-means 
km <- kmeans(pData,centers=2)
# print components of km
print(km)
# plot clusters
plot(pData, col = km$cluster)
# plot centers
points(km$centers, col = 1:2, pch = 8)
```

* there are two obvious clusters. not all points assigned correctly due to wrapping

Question 5
----------

```{r}
library(ElemStatLearn)
data(zip.train)
class(zip.train)
dim(zip.train)
# first column is the digit represented by the remaining 256 columns
head(zip.train)[,1]
```

```{r}
toMatrix <- function(rowN) {
  zip2image(zip.train,rowN)
}
```

```{r}
m8 <- toMatrix(8)
svd8 <- svd(m8)
par(mfrow=c(1,3))
image(t(m8)[,nrow(m8):1]) 
plot(svd8$u[,1],16:1,,xlab="Row",ylab="First left singular vector",pch=19) 
plot(svd8$v[,1],xlab="Column",ylab="First right singular vector",pch=19)
```

```{r}
m18 <- toMatrix(18)
svd18 <- svd(m18)
par(mfrow=c(1,3))
image(t(m18)[,nrow(m18):1]) 
plot(svd18$u[,1],16:1,,xlab="Row",ylab="First left singular vector",pch=19) 
plot(svd18$v[,1],xlab="Column",ylab="First right singular vector",pch=19)
```

```{r}
par(mfrow=c(1,2))
plot(svd8$d,xlab="Column",ylab="Singluar value",pch=19) 
plot(svd8$d^2/sum(svd8$d^2),xlab="Column",ylab="Percent of variance explained",pch=19)
```

```{r}
par(mfrow=c(1,2))
plot(svd18$d,xlab="Column",ylab="Singluar value",pch=19) 
plot(svd18$d^2/sum(svd18$d^2),xlab="Column",ylab="Percent of variance explained",pch=19)
```

